#!/usr/bin/env bash

set -e

. functions

function usage {
	cat <<END
View standard input.

Usage:
  $0 [<options>] [<view option>]

Options:
  --help, -h
    Display this help
END
	exit 2
}

while [[ $# -gt 0 ]]; do
case $1 in
--help | -h)
	usage
	;;
--)
	shift
	break
	;;
*)
	break
	;;
esac
done

exec view "$@" --not-a-term -
